# Generated by Django 3.2.5 on 2021-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('queries', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
